# NOTE: 
# important domains
#   - rt.zerodoc.dev = 96.18.73.74
# ids:
#   - id must be between [1-254]

[ungrouped.hosts]
"rt.zerodoc.dev" = { user = "zdune", ip = "96.18.73.74", host = "zpldune", id = 1 }
#"192.168.1.231"  = { user = "tdune", ip = "162.203.120.155", host = "tp0dune", id = 2 }
"192.168.1.220"  = { user = "vdune", ip = "162.203.120.155", host = "vp0dune", id = 3 }
"192.168.1.224"  = { user = "zdune", ip = "162.203.120.155", host = "zp0dune", id = 4 }
"192.168.1.225"  = { user = "zdune", ip = "162.203.120.155", host = "zp1dune", id = 5 }
"192.168.1.226"  = { user = "zdune", ip = "162.203.120.155", host = "zp2dune", id = 6 }
"170.64.233.32" = { user = "mdune", ip = "170.64.233.32", host = "m0dune-syd1", id = 7 }
"97.107.135.182" = { user = "adune", ip = "97.107.135.182", host = "a0dune-us-east", id = 8 }

[adune.vars]
ansible_ssh_user = "adune"

[adune.hosts]
"97.107.135.182" = { user = "adune", ip = "97.107.135.182" }

[mdune.vars]
ansible_ssh_user = "mdune"

[mdune.hosts]
"170.64.233.32" = { user = "mdune", ip = "170.64.233.32" }

[tdune.vars]
ansible_ssh_user = "tdune"

[tdune.hosts]
# "192.168.1.231" = { user = "tdune", ip = "162.203.120.155" }

[vdune.vars]
ansible_ssh_user = "vdune"

[vdune.hosts]
"192.168.1.220" = { user = "vdune", ip = "162.203.120.155" }

[zdune.vars]
ansible_ssh_user = "zdune"

[zdune.hosts]
"192.168.1.224"  = { user = "zdune", ip = "162.203.120.155" }
"192.168.1.225"  = { user = "zdune", ip = "162.203.120.155" }
"192.168.1.226"  = { user = "zdune", ip = "162.203.120.155" }
"rt.zerodoc.dev" = { user = "zdune", ip = "96.18.73.74" }

[clients]
children = [
  "adune",
  "tdune",
  "vdune",
  "zdune"
]

[net_longview.hosts]
"rt.zerodoc.dev" = { user = "zdune", ip = "96.18.73.74" }

[net_houston.hosts]
# "192.168.1.231" = { user = "tdune", ip = "162.203.120.155" }
"192.168.1.220" = { user = "vdune", ip = "162.203.120.155" }
"192.168.1.224" = { user = "zdune", ip = "162.203.120.155" }
"192.168.1.225" = { user = "zdune", ip = "162.203.120.155" }
"192.168.1.226" = { user = "zdune", ip = "162.203.120.155" }

[net_vps.hosts]
"97.107.135.182" = { user = "adune", ip = "97.107.135.182" }
"170.64.233.32" = { user = "mdune", ip = "170.64.233.32" }

[all]
children = [
  "adune",
  "mdune",
  "tdune",
  "vdune",
  "zdune"
]
