---

- name: Detect SSH port
  import_playbook: basebook/detect-port.yaml

- name: Debugging
  hosts: all

  tasks:
    - name: Testing
      ansible.builtin.debug:
        msg: "{{ 'net_houston' not in hostvars[item].group_names or True }}"
      loop: "{{ groups['net_houston'] }}"
