---

- name: Detect SSH port
  import_playbook: detect-port.yaml

- name: Initialize dune host
  import_playbook: wireguard/spoke.yaml

- name: Create dune services
  hosts: "clients:!mdune"
  become: true

  vars_files:
    - ../vars/vars.yaml
    - ../vars/vars.secrets.yaml

  tasks:
    - name: Create drone volume folder
      ansible.builtin.file:
        path: /root/volume/drone
        state: directory
        mode: '0755'

    - name: Create consul client config
      ansible.builtin.template:
        dest: /etc/consul.d/consul.hcl
        src: consul-client.hcl.j2
        owner: root
        group: root
        mode: '0644'

    - name: Start consul and enable on boot
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started

    - name: Start user systemd instance for {{ hostvars[inventory_hostname].user }}
      ansible.builtin.systemd:
        name: "user@{{ ansible_user_uid }}.service"
        state: started

    - name: Enable rootless podman socket for {{ hostvars[inventory_hostname].user }}
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started
        scope: user
      become: true
      become_user: "{{ hostvars[inventory_hostname].user }}"

    - name: Enable rootful podman socket
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started
        scope: system

    - name: Create nomad client config
      ansible.builtin.template:
        dest: /etc/nomad.d/nomad.hcl
        src: nomad-client.hcl.j2
        owner: root
        group: root
        mode: '0644'

    - name: Create traefik directory
      ansible.builtin.file:
        path: /etc/ssl/traefik
        state: directory
        mode: '0755'

    - name: Start nomad and enable on boot
      ansible.builtin.systemd:
        name: nomad
        enabled: true
        state: started

- name: Create mdune server services
  hosts: mdune
  become: true

  vars_files:
    - ../vars/vars.yaml
    - ../vars/vars.secrets.yaml

  tasks:
    - name: Get wg network info
      ansible.builtin.command: ip -4 addr show dune
      register: wg_net_info
      changed_when: wg_net_info.rc == 0

    - name: Parse wg ip from network info
      ansible.builtin.command:
        cmd: grep -oP '(?<=inet\s)\d+(\.\d+){3}'
        stdin: "{{ wg_net_info.stdout }}"
      register: wg_ip_address
      changed_when: wg_ip_address.rc == 0

    - name: Set local network ip address
      ansible.builtin.set_fact:
        wg_ip: "{{ wg_ip_address.stdout }}"

    - name: Upload consul service file
      ansible.builtin.copy:
        src: ../data/consul.service
        dest: /lib/systemd/system/consul.service
        owner: root
        group: root
        mode: '0644'

    - name: Create consul server config
      ansible.builtin.template:
        dest: /etc/consul.d/consul.hcl
        src: consul-server.hcl.j2
        owner: root
        group: root
        mode: '0644'
      notify: Restart consul

    - name: Start consul and enable on boot
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started

    - name: Start user systemd instance for {{ hostvars[inventory_hostname].user }}
      ansible.builtin.systemd:
        name: "user@{{ ansible_user_uid }}.service"
        state: started

    - name: Enable rootless podman socket for {{ hostvars[inventory_hostname].user }}
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started
        scope: user
      become: true
      become_user: "{{ hostvars[inventory_hostname].user }}"

    - name: Create nomad server config
      ansible.builtin.template:
        dest: /etc/nomad.d/nomad.hcl
        src: nomad-server.hcl.j2
        owner: root
        group: root
        mode: '0644'
      notify: Restart nomad

    - name: Start nomad and enable on boot
      ansible.builtin.systemd:
        name: nomad
        enabled: true
        state: started

  handlers:
    - name: Restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted

    - name: Restart nomad
      ansible.builtin.systemd:
        name: nomad
        state: restarted
