- name: Install sudo via apt
  ansible.builtin.apt:
    name: sudo

- name: Create group for ssh users
  ansible.builtin.group:
    name: sshusers

- name: Create group for su users
  ansible.builtin.group:
    name: suusers

- name: Create group for sudo users
  ansible.builtin.group:
    name: sudousers

- name: Create podman group
  ansible.builtin.group:
    name: podman

- name: Create new user with password, add to groups
  become: true
  ansible.builtin.user:
    name: "{{ hostvars[inventory_hostname].user }}"
    password: "{{ user_pw | password_hash('sha512') }}"
    groups: "sshusers, sudousers, suusers, podman"
    shell: /bin/bash

- name: Configure subuid for primary user
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subuid
    mode: umask
    regexp: '^{{ hostvars[inventory_hostname].user }}:'
    line: '{{ hostvars[inventory_hostname].user }}:100000:65536'
    create: true

- name: Configure subgid for primary user
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subgid
    mode: umask
    regexp: '^{{ hostvars[inventory_hostname].user }}:'
    line: '{{ hostvars[inventory_hostname].user }}:100000:65536'
    create: true

- name: Limit sudo to sudousers groups
  become: true
  ansible.builtin.lineinfile:
    create: true
    mode: '0440'
    path: /etc/sudoers
    regexp: '^%sudousers'
    line: '%sudousers   ALL=(ALL:ALL) ALL'

- name: Limit who can use su
  become: true
  register: requirements_sustd
  ansible.builtin.shell: |
    sudo dpkg-statoverride --update --add root suusers 4750 /bin/su
  changed_when: requirements_sustd.rc == 0
  failed_when:
    - requirements_sustd.rc != 0
    - '"exist" not in requirements_sustd.stderr' # this has to be changed: unsure how to skip the "already exist" error in other languages

- name: Passwordless sudo for new user
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ hostvars[inventory_hostname].user }}'
    line: '{{ hostvars[inventory_hostname].user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: '0440'
    create: true
    validate: 'visudo -cf %s'

- name: Add authorized keys for new user
  become: true
  ansible.posix.authorized_key:
    user: "{{ hostvars[inventory_hostname].user }}"
    key: "{{ lookup('file', '../../../../data/emergenkey.pub') }}"

- name: Create extra users with password, add to groups
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ user_pw | password_hash('sha512') }}"
    groups: "sshusers, sudousers, suusers, podman"
    shell: /bin/bash
  loop: "{{ hostvars[inventory_hostname].extra_users | default([]) }}"

- name: Configure subuid for extra users
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subuid
    mode: umask
    regexp: '^{{ item }}:'
    line: '{{ item }}:{{ 165536 + (ansible_loop.index0 * 65536) }}:65536'
    create: true
  loop: "{{ hostvars[inventory_hostname].extra_users | default([]) }}"
  loop_control:
    extended: true

- name: Configure subgid for extra users
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subgid
    mode: umask
    regexp: '^{{ item }}:'
    line: '{{ item }}:{{ 165536 + (ansible_loop.index0 * 65536) }}:65536'
    create: true
  loop: "{{ hostvars[inventory_hostname].extra_users | default([]) }}"
  loop_control:
    extended: true

- name: Passwordless sudo for extra users
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: '0440'
    create: true
    validate: 'visudo -cf %s'
  loop: "{{ hostvars[inventory_hostname].extra_users | default([]) }}"

- name: Add authorized keys for extra users
  become: true
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '../../../../data/emergenkey.pub') }}"
  loop: "{{ hostvars[inventory_hostname].extra_users | default([]) }}"

- name: Add reset iptables sh file
  become: true
  ansible.builtin.copy:
    src: ../../../../data/reset-iptables.sh
    dest: ~/reset-iptables.sh
    owner: root
    group: root
    mode: '0755'

- name: Run reset iptables
  become: true
  become_user: root
  register: requirements_reset
  ansible.builtin.command: bash /root/reset-iptables.sh
  changed_when: requirements_reset.rc == 0
