---

- name: Setup and verify wg hub
  import_playbook: hub.yaml

- name: Create wg spokes
  hosts: "clients:!mdune"
  become: true
  become_user: root

  vars_files:
    - ../../vars/vars.yaml
    - ../../vars/vars.secrets.yaml

  tasks:
    - name: Create spoke wireguard config
      ansible.builtin.template:
        dest: /etc/wireguard/dune.conf
        src: spoke.conf.j2
        owner: root
        group: root
        mode: '0600'
      notify: Restart wireguard
      no_log: true

    - name: Enable wireguard on boot
      ansible.builtin.systemd:
        name: wg-quick@dune
        enabled: true

    - name: Check if wireguard interface exists
      ansible.builtin.command: ip link show dune
      register: wg_iface_check
      changed_when: false
      failed_when: false

    - name: Start or restart wireguard
      ansible.builtin.systemd:
        name: wg-quick@dune
        state: "{{ 'restarted' if wg_iface_check.rc != 0 else 'started' }}"

    - name: Get wg network info
      ansible.builtin.command: ip -4 addr show dune
      register: wg_net_info
      changed_when: false

    - name: Parse wg ip from network info
      ansible.builtin.command:
        cmd: grep -oP '(?<=inet\s)\d+(\.\d+){3}'
        stdin: "{{ wg_net_info.stdout }}"
      register: wg_ip_address
      changed_when: false

    - name: Set local network ip address
      ansible.builtin.set_fact:
        wg_ip: "{{ wg_ip_address.stdout }}"

  handlers:
    - name: Restart wireguard
      ansible.builtin.shell: wg-quick down dune; wg-quick up dune
      args:
        executable: /bin/bash
      register: restart
      changed_when: restart.rc == 0
